# Generated by Django 5.1 on 2024-10-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=15, unique=True)),
                ('seat_type', models.CharField(choices=[('seater', 'Seater'), ('sleeper', 'Sleeper')], max_length=15)),
                ('seat_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=100, unique=True)),
                ('booking_date', models.DateField()),
                ('start_point', models.CharField(max_length=50)),
                ('end_point', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_no', models.CharField(default='L1', max_length=100)),
                ('booking_status', models.CharField(choices=[('success', 'Success'), ('cancelled', 'Cancelled')], default='success', max_length=15)),
                ('schedule', models.CharField(default='00.00 - 06.00', max_length=50)),
            ],
            options={
                'unique_together': {('booking_date', 'start_point', 'end_point', 'seat_no', 'schedule')},
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('bookings', models.ManyToManyField(related_name='passengers', to='Bus_reservations.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_route', models.CharField(choices=[('chennai', 'Chennai'), ('coimbatore', 'Coimbatore'), ('bangalore', 'Bangalore')], max_length=50)),
                ('end_route', models.CharField(choices=[('chennai', 'Chennai'), ('coimbatore', 'Coimbatore'), ('bangalore', 'Bangalore')], max_length=50)),
            ],
            options={
                'unique_together': {('start_route', 'end_route')},
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('bus_no', models.CharField(max_length=20, unique=True)),
                ('bus_name', models.CharField(max_length=20)),
                ('schedule', models.CharField(choices=[('schedule_one', '00.00 - 06.00'), ('schedule_two', '07.00 - 12.00'), ('schedule_three', '13.00 - 18.00'), ('schedule_four', '19.00 - 24.00')], default=('schedule_one', '00.00 - 06.00'), max_length=50)),
                ('routes', models.ManyToManyField(related_name='Buses', to='Bus_reservations.route')),
                ('seats', models.ManyToManyField(related_name='Buses', to='Bus_reservations.seat')),
            ],
        ),
    ]
