# Generated by Django 5.1 on 2024-11-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_reservations', '0003_location_alter_route_end_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='routes',
            field=models.ManyToManyField(related_name='Buses', related_query_name='bus', to='Bus_reservations.route'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seats',
            field=models.ManyToManyField(related_name='Buses', related_query_name='bus', to='Bus_reservations.seat'),
        ),
    ]
